# =================================================================
#
# Authors: Just van den Broecke <justb4@gmail.com>>
#          Jorge Samuel Mendes de Jesus <jorge.dejesus@geocat.net>
#          Tom Kraldis <tomkralidis@gmail.com>
#
# Copyright (c) 2019 Just van den Broecke
# Copyright (c) 2019 Jorge Samuel Mendes de Jesus
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
  bind:
    host: localhost
    port: 80
  url: http://localhost:5011
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  language: en-US
  cors: true
  pretty_print: true
  limit: 10
  # templates: /path/to/templates
  map:
    url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
    attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
  level: DEBUG
  logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: pygeoapi default instance
    description: pygeoapi provides an API to geospatial data
    keywords:
      - geospatial
      - data
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://example.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Organization Name
    url: https://pygeoapi.io
  contact:
    name: Lastname, Firstname
    position: Position Title
    address: Mailing Address
    city: City
    stateorprovince: Administrative Area
    postalcode: Zip or Postal Code
    country: Country
    phone: +xx-xxx-xxx-xxxx
    fax: +xx-xxx-xxx-xxxx
    email: you@example.org
    url: Contact URL
    hours: Hours of Service
    instructions: During hours of service.  Off on weekends.
    role: pointOfContact

resources:
  reference_geometries:
    type: collection
    title: Reference geometries
    description: Reference geometries on which the visualization of indicators are based on.
    keywords:
      - reference geometries
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of reference geometries
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers: &db-rafvinert
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [public]
        id_field: id
        table: reference_geometries
        geom_field: geometry

  mean-age:
    type: collection
    title: Mean age
    description: Mean age of all citizens based on specific reference geometries.
    keywords:
      - mean age
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of mean age
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [ public ]
        id_field: id
        table: mean_ages
        geom_field: geometry

  median-age:
    type: collection
    title: Median age
    description: Median age of all citizens based on specific reference geometries.
    keywords:
      - median age
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of median age
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [ public ]
        id_field: id
        table: median_ages
        geom_field: geometry

  greying_index:
    type: collection
    title: Greying Index
    description: Greying Index of all citizens based on specific reference geometries.
    keywords:
      - greying index
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of Greying Index
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [ public ]
        id_field: id
        table: greying_index
        geom_field: geometry

  child_dependency_ratio:
    type: collection
    title: Child Dependency Ratio
    description: Child Dependency Ratio in the specific reference geometries.
    keywords:
      - child dependency ratio
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of Child Dependency Ratio
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [ public ]
        id_field: id
        table: child_dependency_ratio
        geom_field: geometry

  aged_dependency_ratio:
    type: collection
    title: Aged Dependency Ratio
    description: Aged Dependency Ratio in the specific reference geometries.
    keywords:
      - aged dependency ratio
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of Aged Dependency Ratio
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [ public ]
        id_field: id
        table: aged_dependency_ratio
        geom_field: geometry

  total_dependency_ratio:
    type: collection
    title: Total Dependency Ratio
    description: Total Dependency Ratio in the specific reference geometries.
    keywords:
      - total dependency ratio
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of Total Dependency Ratio
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [ public ]
        id_field: id
        table: total_dependency_ratio
        geom_field: geometry

  remancence-building:
    type: collection
    title: Remanence Buildings
    description:
    keywords:
      -
      - monitoring
    links:
      - type: text/html
        rel: self
        title: Collection of Total Dependency Ratio
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: pgsql
          port: 5432
          dbname: monitoring
          user: sail
          password: password
          search_path: [ public ]
        id_field: id
        table: remanence_buildings
        geom_field: geometry

  walkability-detail:
    type: collection
    title: Walkability Detail
    description: Walkability Detail
    keywords:
      - walkability
    links:
      - type: text/html
        rel: self
        title: Collection of Total Dependency Ratio
        href: https://example.com
    extents:
      spatial:
        bbox:
          [
            7.711151594999341,
            49.47714395615903,
            7.815457562211972,
            49.522819495461825,
          ]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: GeoJSON
        data: ./data/walkscore_detail.geojson
